apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: "monitoring-grafana"
    kubernetes.io/cluster-service: "true"
  name: monitoring-grafana
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    name: influxGrafana
