apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-registry-proxy
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      name: kube-registry-proxy
      labels:
        daemon: kube-registry-proxy
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kube-registry-proxy
        image: kubernetesonarm/kube-registry-proxy-arm:0.4
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
        env:
        - name: REGISTRY_HOST
          value: kube-registry.kube-system.svc.cluster.local
        - name: REGISTRY_PORT
          value: "5000"
        - name: FORWARD_PORT
          value: "5000"
        ports:
        - name: registry
          containerPort: 5000
          hostPort: 5000
