apiVersion: v1
kind: Config
preferences: {}
current-context: kubernetes
clusters:
- cluster:
    server: https://prometheus.lan.mccorkell.me.uk:6443
    certificate-authority: /etc/kubernetes/ssl/ca.pem
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: prometheus
  name: kubernetes
users:
- name: prometheus
  user:
    client-certificate: /etc/kubernetes/ssl/prometheus.pem
    client-key: /etc/kubernetes/ssl/prometheus-key.pem
